import iphone14Img from "../assets/samsung-galaxy-tab-s8-ultra-render-design-notch-feat.webp";
export const items = [
  {
    id: 1,
    category: "mobiles",
    title: "Apple iphone 14",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iphone 14 (128 GB) - Blue",
    price: 29999,
  },
  {
    id: 2,
    category: "mobiles",
    title: "Apple iphone 12",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iphone 14 (128 GB) - Blue",
    price: 39999,
  },
  {
    id: 3,
    category: "mobiles",
    title: "Apple iphone 15",
    imgSrc: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Apple iphone 14 (128 GB) - Blue",
    price: 59999,
  },
  {
    id: 4,
    category: "laptops",
    title: "Xiomi[SmartChoice] notebook pro",
    imgSrc: "https://m.media-amazon.com/images/I/61vFO3R5UNL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 39999,
  },
  {
    id: 5,
    category: "laptops",
    title: "Xiomi [SmartChoice] notebook pro",
    imgSrc: "https://m.media-amazon.com/images/I/61vFO3R5UNL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 49999,
  },
  {
    id: 6,
    category: "laptops",
    title: "Xiomi[SmartChoice] notebook pro",
    imgSrc: "https://m.media-amazon.com/images/I/61vFO3R5UNL._SL1500_.jpg",
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 59999,
  },
  {
    id: 7,
    category: "tablets",
    title: "Samsung Tabs",
    imgSrc: iphone14Img,
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 29999,
  },
  {
    id: 8,
    category: "tablets",
    title: "Xiomi Samsung Tabs",
    imgSrc: iphone14Img,
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 39999,
  },
  {
    id: 9,
    category: "tablets",
    title: "Xiomi Samsung Tabs",
    imgSrc: iphone14Img,
    amazonLink: "https://amzn.to/3PuckZp",
    description: "Xiomi[SmartChoice] notebook pro",
    price: 59999,
  },
];
